### ISSUE TITLE
reconstruction_neighbors2 or reconstruction_neighbors?

### ISSUE THREAD

**Issue by YingtongDou** [Graph-COM/GAD-NR#1]
Hi Amit,

Congrats on the acceptance of the work! I have a question about the two neighbor reconstruction functions. It seems that you only use the `reconstruction_neighbors2` in the `neigbhor_decoder`, leaving the `reconstruction_neighbors` function and `sample_neighbors` useless, is there any insight behind it?

**Comment by AmitRoy7781** [comment]
Hi Yingtong,

The function `reconstruction_neighbors` which is adapted from the original NWR-GAE paper reconstructs the neighborhood for each node using a for loop which is slow for large datasets whereas the `reconstruction_neighbors2` reconstructs the neighborhood using full batch implementation using the SAGEConv and PNAConv to parallely compute the mean and standard deviation of neighbor features for all node.

**Comment by YingtongDou** [comment]
Thank you!
