### ISSUE TITLE
Singular matrix problem 

### ISSUE THREAD

**Issue by Tlhey** [Graph-COM/GAD-NR#6]
Have you encounter the problem of inverse of a matrix? I noticed that you add an identity matrix, however, I still encounter the singular matrix problem when reproducing the result.

**Comment by AmitRoy7781** [comment]
You can try normalizing the representations or changing the type of the GNN. It can also be caused due to the initialization of the parameters, can probably try using different seeds.

**Comment by Tlhey** [comment]
After I changed a smaller learning rate and change it to another gpu, it magically worked! thank you!
